name: Build and Deploy Node.js App to Azure Web App - Re-Recipe

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Step 3: Install and Build Angular (Frontend)
      - name: Install and Build Angular Frontend
        run: |
          cd cli/cook/src
          npm install
          npm run build

      # Step 4: Install and Build App Server (Backend)
      - name: Install and Build Backend Server
        run: |
          cd MongooseDB
          npm install
          npm run build

      # Step 5: Zip artifact for deployment
      - name: Zip artifact for deployment
        run: |
          cd ..
          zip -r release.zip cli/cook/src/dist MongooseDB

      # Step 6: Upload artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: re-recipe-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: re-recipe-app

      # Step 2: Unzip artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Re-Recipe'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
