name: Build and Deploy Node.js and Angular App to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install and build backend (MongooseDB)
      - name: Build Backend
        working-directory: ./MongooseDB
        run: |
          npm install
          npm run build

      # Install and build frontend (Angular CLI)
      - name: Build Frontend
        working-directory: ./cli/recipes/src/app
        run: |
          npm install
          npm run build --prod

      # Zip artifacts for deployment
      - name: Zip artifacts
        run: zip -r release.zip ./MongooseDB ./cli/recipes/src/app/dist

      # Upload artifacts for the deploy job
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Download artifact from the build job
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      # Unzip artifact for deployment
      - name: Unzip artifact
        run: unzip release.zip

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Re-Recipe'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
