name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Step 3: Install dependencies and build backend
      - name: Install and build backend
        working-directory: MongooseDB
        run: |
          npm install
          npm run build

      # Step 4: Install dependencies and build frontend
      - name: Install and build frontend
        working-directory: cli/recipes/src/app
        run: |
          npm install
          npm run build --if-present

      # Step 5: Zip built artifacts
      - name: Zip artifacts
        run: zip -r app.zip ./MongooseDB ./cli/recipes/dist/recipes

      # Step 6: Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact

      # Step 2: Deploy to Azure via FTP
      - name: Deploy to Azure Web App via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: 're-recipe-geh7akd0dsa2d4cj.westus-01.azurewebsites.net'
          username: ${{ secrets.FTPS_USERNAME }}
          password: ${{ secrets.FTPS_PASSWORD }}
          local-dir: './'
          server-dir: '/site/wwwroot'
